DATA SEGMENT
    SOURCE DB 01H, 02H, 03H, 04H, 05H
    DEST DB 10 DUP(0)
DATA ENDS

CODE SEGMENT
    START:
        MOV AX, DATA
        MOV DS, AX      ;LOAD DS WITH "DATA"
        MOV ES, AX      ;OVERLAP ES AND DS
        LEA SI, SOURCE  ;MOVE ADDRESS OF SOURCE TO SI
        LEA DI, DEST    ;MOVE ADDRESS OF DESTINATION TO DI
        MOV CX, 05H     ;LOAD CX WITH SIZE OF SOURCE
        CLD             ;CLEAR DIRECTION FLAG
        REP MOVSB       ;COPY CONTENTS FROM SOURCE TO DESTINATION
        HLT
CODE ENDS
    END START
        